apiVersion: apps/v1
kind: Deployment
metadata:
  name: simchaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simchaapp
  template:
    metadata:
      labels:
        app: simchaapp
    spec:
      containers:
      - name: simchaapp
        image: vizel014/app:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simchaapp
spec:
  type: NodePort
  selector:
    app: simchaapp
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30006

